"use client";

import NavBar from "@/components/NavBar";
import "./globals.css";

import { KvibProvider } from "@kvib/react";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <KvibProvider>
          <NavBar />
          {children}
        </KvibProvider>
      </body>
    </html>
  );
}
